### ISSUE TITLE
[Collaborative Lesson 1] 사용자 입력 범위 변경

### ISSUE THREAD

**Issue by huinalam** [rbsejin/PatternDesign#14]
# [Collaborative Lesson 1] 사용자 입력 범위 변경

Collaborative Lesson은 다른 레슨자의 코드를 수정하여 과제를 수행해야 한다.

1. 사용자가 입력할 수 있는 값인 1-100의 값을 1-50으로 수정한다.

- 제한사항
  - `master` 브랜치가 아닌 `dev` 브랜치에서 작업해야 한다.
  - 수정 후, 오류가 없어야 한다.

**Comment by huinalam** [comment]
@rbsejin 님, https://github.com/bykauienm/git_test 에서 작업 완료 후, https://github.com/bykauienm/git_test/issues/16 에 답글을 달아주면 됩니다.
질문이 있거나 완료가 되면, 서로 답변을 해주시면 됩니다.
완료 여부는 레포지토리 관리자가 해주시면 됩니다.
저는 서포트 역할로 조언하도록 할께요.

**Comment by rbsejin** [comment]
최대 최소값을 윤배님이 하신 것 처럼 enum 으로 선언하는 것이 좋을 것 같아요!

**Comment by huinalam** [comment]
@rbsejin 혹시나해서 코맨트 달자면^^... 자신의 코드를 수정하는 것이 아닌 상대방의 코드를 수정하는 겁니다. 혹시 푸시가 안되시면, 서로 Settings에 들어가서 Collaborators에 서로의 아이디를 등록해주세요.

**Comment by rbsejin** [comment]
네 저는 등록 해놨습니다!

**Comment by bykauienm** [comment]
수정 완료했습니다. 저도 collaborators에 초대 했습니다.

**Comment by rbsejin** [comment]
잘 수정되었습니다

**Comment by huinalam** [comment]
@rbsejin @bykauienm 
제가 미처 못보고 지나친 부분이 있었네요.
하나의 집합으로 묶여서 좋긴 하지만, int로 형 변환을 굳이 해야한다니 좀 불편하지 않을까 싶네요.
static class에 const int property로 적용하면 어떨까 싶은데요. 이름이나 접근 면에서 직관성이 같고, 형변환도 굳이 필요없으니 편하구요. 어떻게 생각하시나요?

**Comment by bykauienm** [comment]
RandomDiamondPattern 추가하고 Pull Request 요청했습니다.
규빈님이 제안해준 것도 더 괜찮아 보여 Min Max도 변경해봤습니다.~

**Comment by huinalam** [comment]
끘!
