### ISSUE TITLE
[Final Lesson] Pull Request & Code Review

### ISSUE THREAD

**Issue by huinalam** [rbsejin/PatternDesign#17]
# [Final Lesson] Pull Request & Code Review

1. 다른 개발자가 자신의 프로젝트에 요청한 pull request를 보고 코드리뷰 후 merge를 수행한다.

- 힌트
  - 다른 개발자의 repository에서 코드리뷰를 해주면 된다.

**Comment by huinalam** [comment]
코드 리뷰는 내일 오후 7시에 오프라인에서 진행합니다 ^^
PR까지 부탁할께요.

**Comment by rbsejin** [comment]
@huinalam 규빈님 5개월 가량 레슨을 해주셔서 정말 감사드려요. 일반 책이나 강의에서는 결코 얻을 수 없는 것을 많이 얻어가요. 제일 처음은 git사용, 그리고 컨벤션(네이밍), 그리고 프로젝트에서 OOP의 개념을 어떻게 활용하는지, 협업하기 위해서 코드는 어떻게 작성해야하는지, 그리고 태어나서 처음들어본 테스트코드 등 정말 많은 것을 배워갔네요. 그리고 그것들의 의미에 대해서 생각을 많이 해보게 되었습니다.
 물론 실력이 아주 많이 늘었을 것 같지는 않아요. 하지만 기본 자세, 방향을 잡는데 무척 큰 도움이 되었습니다. 실력은 앞으로 제가 채워나가면 되겠죠. 제가 믿을 만한 사람에게 배우고 시작할 수 있어서 매우 뜻깊었습니다. 저도 규빈님과 같은 시니어가 되어서 저의 재능을 나눌 수 있는 위치가 되었으면 좋겠습니다.
 마지막으로 저녁에 회식하면서 규빈님이 왜 프로그래머가 되고 싶냐는 질문이 계속 생각이 나네요. 나름 답을 얻고 열심히 한다고 생각했었는데 질문에 당당하게 답을 못한 스스로를 보면서 내가 또 방향을 잠시 잃었구나 하고 생각하게 되었습니다. 앞으로 내가 왜 프로그래밍이 하고 싶은지, 어떤 프로그래머가 되고 싶은지에 대해서 다시 진지하게 생각해보려고 합니다.  코딩 완전 초보자에게 이런 기회를 주셔서 너무 감사하고, 그 동안 수고 정말 많으셨습니다.

@bykauienm 윤배님을 이번 프로젝트를 통해 만날 수 있어서 너무 기뻤습니다.  프로젝트를 하면서 이만하면 완벽하게 했다고 생각했는데 나중에 윤배님 프로젝트를 보면서 저의 부족함을 많이 느꼈어요. 혼자가 아니라 같이 할 수 있어서 더 의미있고 재미있었습니다. 앞으로 규빈님과 같이 일하시게 될 텐데 지금 보다 더 성장할 수 있었으면 합니다. 감사합니다.

**Comment by huinalam** [comment]
@rbsejin 님.

레슨을 진행하면서 많은 고민이 있었네요. 이게 세진님께 정말 필요한 레슨일까. 이것보다 더 나은 게 있지 않을까 등등. 어쩌면 세진님께서 스스로 필요한 것을 정의하지 못한데서 나온 혼란이 아닌가 싶기도 하네요.

세진님과 레슨을 진행하며 가장 인상깊었던 장면은, 중간 회고 후 코드를 다시 구현했을 때였어요. 그만큼 스스로 무엇이 더 나은 것인지 끊임없이 고민했기 때문에 나온 행동이지 않나 싶었어요. 자기가 구현한 코드를 다시 짜는 건 에너지가 정말 많이 드는 일이거든요^^

진행하는 와중에 스스로의 진로에 대한 고민을 가지고 계셨을 것 같았어요. 레슨의 경험에 지나치게 구애받지는 마시고, 뭐든 해보셨으면 좋겠어요.  그러면서 스스로 가지고 있던 질문과 하는 행동이 하나의 맥락으로 묶여간다면, 그곳에 세진님이 뜻하는 길이 있지 않을까 싶네요.

수고 많으셨습니다 :)
